### ISSUE TITLE
broken table when using umlauts äöü..

### ISSUE THREAD

**Issue by rtulke** [Robpol86/terminaltables#1]
I tested terminaltables with umlauts and i get an broken table.

**Comment by Robpol86** [comment]
Hmm, I'm having trouble reproducing the problem. If you were using terminaltables together with [colorclass](https://github.com/Robpol86/colorclass) then I fixed a unicode problem with that library earlier today. However I didn't change any of terminaltables' code and it seems to be working for me:

```python
from terminaltables import AsciiTable
table_data = [
    ['Name', 'Color', 'Type'],
    ['Avocado', 'green', 'nut'],
    [u'Cupuaçu', 'yellow', 'fruit'],
    [u'äöüß', '', 'neither'],
]
table = AsciiTable(table_data, 'Foods')
print table.table

+Foods----+--------+---------+
| Name    | Color  | Type    |
+---------+--------+---------+
| Avocado | green  | nut     |
| Cupuaçu | yellow | fruit   |
| äöüß    |        | neither |
+---------+--------+---------+
```

Can you tell me the problem you were seeing, pasting the output? If you can, also provide example code so I may try to reproduce it on my machine.

**Comment by rtulke** [comment]
Hmm i used then terminaltables version from pip

**Comment by rtulke** [comment]
a  :D it works with u'fööö' :-)

**Comment by Robpol86** [comment]
Your code seems to work fine on my OS X 10.9.5 with 2.7.6. The table was aligned properly.

```
[tw-mbp ~]$ virtualenv ~/virtualenvs/test_tt
New python executable in /Users/me/virtualenvs/test_tt/bin/python2.7
Also creating executable in /Users/me/virtualenvs/test_tt/bin/python
Installing setuptools, pip...done.
[tw-mbp ~]$ . ~/virtualenvs/test_tt/bin/activate
(test_tt)[tw-mbp ~]$ pip freeze
wsgiref==0.1.2
(test_tt)[tw-mbp ~]$ pip install terminaltables
Downloading/unpacking terminaltables
  Downloading terminaltables-1.1.1.tar.gz
  Running setup.py (path:/Users/me/virtualenvs/test_tt/build/terminaltables/setup.py) egg_info for package terminaltables
    
Installing collected packages: terminaltables
  Running setup.py install for terminaltables
    
Successfully installed terminaltables
Cleaning up...
(test_tt)[tw-mbp ~]$ pip freeze
terminaltables==1.1.1
wsgiref==0.1.2
(test_tt)[tw-mbp ~]$ cat my.conf 
[bug_tracker]
description = alles über bugtracker
url = http://localhost:8080/bugs/
location = /home/repo/bug_tracker
username = dhellmann
password = SECRET

[wiki]
description = foo bar bla
location = /home/repo/wiki
url = http://localhost:8080/wiki/
username = dhellmann
password = SECRET
(test_tt)[tw-mbp ~]$ python my.py 
 id  repository   url                          description             location               
 1   bug_tracker  http://localhost:8080/bugs/  alles über bugtracker  /home/repo/bug_tracker 
 2   wiki         http://localhost:8080/wiki/  foo bar bla             /home/repo/wiki        
(test_tt)[tw-mbp ~]$ python -V
Python 2.7.6
```

**Comment by rtulke** [comment]
mh my misstake i forgot the u' infront the umlaut thx!

**Comment by Robpol86** [comment]
Ah cool, no worries.

**Comment by rtulke** [comment]
After a long time ....

sorry but i try to test your code ... and i see in your code has the same broken table :) please enable tableline and than you will see the broken table it is one char ...

**Comment by Robpol86** [comment]
Still works fine for me. Can you post a screen shot?
![screen shot 2015-06-23 at 8 57 13 am](https://cloud.githubusercontent.com/assets/3413339/8310616/f2631000-1985-11e5-8f5e-17c9ee9a9fce.png)

**Comment by rtulke** [comment]
Sorry here is my Screenshot i forgot!

![hg_table_shot](https://cloud.githubusercontent.com/assets/620092/9082509/d78354d8-3b64-11e5-921a-8075bb5a227c.PNG)

**Comment by rtulke** [comment]
in the first column id: (15 and 16) is an umlaut "ü" in second column and it seems like the break in my table
