### ISSUE TITLE
combine terminaltables and prettytables?

### ISSUE THREAD

**Issue by retsyo** [Robpol86/terminaltables#37]
https://github.com/smeggingsmegger/VeryPrettyTable can do more things like excel, for example

1. get column(s). x.get_string(fields=["City name", "Population"])
2. get row(s). x.get_string(start=1,end=4)
3. sort. x.get_string(sortby="Population")
4. and more

this is useful to extract and display info on a small dos console

So, can terminaltables use prettytables' such function?

or, is there a package for dos console on windows so that we can render big tables, which support 
1. use arrow key to navigate it
2. support CJK

Thanks

**Comment by Robpol86** [comment]
This is out of scope for terminaltables. Terminaltables is more about displaying info from data in your application that you've already parsed, not about reading/parsing data from files.
