### ISSUE TITLE
WindowsTable and WindowsDoubleTable causing exception

### ISSUE THREAD

**Issue by pjc42** [Robpol86/terminaltables#4]
Robpol

I'm a bit of newbie so this may be simple user error. However, on a Windows 7/64 with Anaconda python 3.4, I can only get AsciiTables to work. DoubleTable and other fancy tables fail with various encoding errors.

I installed terminaltables-1.1.1 via pip

Here is an example of the console output for example1.py

-------------------------- snip
B:\python\anaconda3\envs\testTable\python.exe D:/wspace-git/_python/terminaltables/example1.py

Traceback (most recent call last):
  File "D:/wspace-git/_python/terminaltables/example1.py", line 19, in <module>
    print(table.table)
  File "B:\python\anaconda3\envs\testTable\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2554' in position 0: character maps to <undefined>
----------------------- end snip

Any idea on what I may be missing?

Many thanks, Peter

**Comment by Robpol86** [comment]
Can you try it with regular Python on Windows?
